### ISSUE TITLE
Plan for summer vacation

### ISSUE THREAD

**Issue by HcPlu** [HcPluTeam/cs309_proj#3]
游戏的初步设计
1.情节，故事
2.内嵌小游戏的选择
3.游戏引擎的选择和初步学习
4.美术素材

**Comment by HcPlu** [comment]
了解Mozart的生平故事
可以观赏电影《莫扎特传》，音乐剧《莫扎特》
了解一些Mozart的作品，创作背景

**Comment by sunnyswag** [comment]
哇哦,传奇莫扎特
